# Generated by Django 6.0.4 on 2026-05-05 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactinfo',
            table='em_users_contact_info',
        ),
        migrations.AlterModelTable(
            name='contacttype',
            table='em_users_contact_type',
        ),
        migrations.AlterModelTable(
            name='user',
            table='em_users_users',
        ),
    ]
