# Generated by Django 6.0.4 on 2026-05-05 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listing',
            table='em_listings_listing',
        ),
        migrations.AlterModelTable(
            name='location',
            table='em_listings_location',
        ),
        migrations.AlterModelTable(
            name='property',
            table='em_listings_property',
        ),
        migrations.AlterModelTable(
            name='propertytype',
            table='em_listings_property_type',
        ),
    ]
