# Generated by Django 6.0.4 on 2026-05-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_updated_at_alter_location_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
