# Generated by Django 6.0.4 on 2026-05-05 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='em_bookings_booking',
        ),
    ]
