# Generated by Django 6.0.4 on 2026-05-12 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_table'),
        ('listings', '0004_alter_property_location_alter_property_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
