# Generated by Django 6.0.4 on 2026-05-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_listing_alter_booking_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
