# Generated by Django 6.0.4 on 2026-05-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='guest_id',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='guest_agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='guest_ip',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
