# Generated by Django 6.0.4 on 2026-05-05 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='em_reviews_review',
        ),
    ]
