# Generated by Django 6.0.4 on 2026-05-16 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_actual_end_date'),
        ('reviews', '0003_alter_review_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('booking', 'user'), name='unique_review_per_booking_user'),
        ),
    ]
